# Copyright 2020 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Tasks for installing AWX-CLI
- name: Add AWX CLI repo
  block:
    - name: Get repo
      get_url:
        url: "{{ awx_cli_repo }}"
        dest: "{{ awx_cli_repo_path }}"
    - name: Disable gpgcheck
      replace:
        path: "{{ awx_cli_repo_path }}"
        regexp: 'gpgcheck=1'
        replace: 'gpgcheck=0'
  tags: install

- name: Install AWX-CLI
  package:
    name: ansible-tower-cli
    state: present
  tags: install
